### ISSUE TITLE
Connection refused Errno 111

### ISSUE THREAD

**Issue by Domoteek** [ypid/lgcommander#5] opened 2017-03-15 20:12 UTC
Hi , 
I try all script all the Github. 
Alone your script work a little but i have some problem.

`root@raspberrypi:/home/pi/lgcommander# python3 lg.py
# DEBUG: Returned: HTTP/1.1 200 OK
Location: http://192.168.1.100:1909/
Cache-Control: max-age=1800
Server: Linux/i686 UPnP/1,0 DLNADOC/1.50 LGE WebOS TV/Version 0.9
EXT:
USN: uuid:xxxxx::urn:schemas-upnp-org:device:MediaRenderer:1
ST: urn:schemas-upnp-org:device:MediaRenderer:1
Date: Wed, 15 Mar 2017 20:08:17 GMT
DLNADeviceName.lge.com: %5bLG%5d%20webOS%20TV

# DEBUG: Found device: 192.168.1.100
# INFO: Using device: 192.168.1.100 over transport protocol: 8080/tcp
# DEBUG: Detecting accepted protocol.
# DEBUG: Trying to connect to port 3000/tcp
Traceback (most recent call last):
  File "lg.py", line 348, in <module>
    main()
  File "lg.py", line 305, in main
    protocol=user_parms.protocol)
  File "lg.py", line 70, in __init__
    self.auto_detect_accepted_protocol()
  File "lg.py", line 119, in auto_detect_accepted_protocol
    raise Exception("Protocol not supported. See https://github.com/ypid/lgcommander/issues/1")
Exception: Protocol not supported. See https://github.com/ypid/lgcommander/issues/1
`
When i try  roap 

`root@raspberrypi:/home/pi/lgcommander# python3 lg.py -P roap
# DEBUG: Returned: HTTP/1.1 200 OK
Location: http://192.168.1.100:1909/
Cache-Control: max-age=1800
Server: Linux/i686 UPnP/1,0 DLNADOC/1.50 LGE WebOS TV/Version 0.9
EXT:
USN: uuid:92eaf68f-ee7c-55f9-28ea-aa778c67192b::urn:schemas-upnp-org:device:MediaRenderer:1
ST: urn:schemas-upnp-org:device:MediaRenderer:1
Date: Wed, 15 Mar 2017 20:09:41 GMT
DLNADeviceName.lge.com: %5bLG%5d%20webOS%20TV

# DEBUG: Found device: 192.168.1.100
# INFO: Using device: 192.168.1.100 over transport protocol: 8080/tcp
# DEBUG: No valid pairing key from user. Asking user …
# DEBUG: Request device to show key on screen.
Traceback (most recent call last):
  File "lg.py", line 348, in <module>
    main()
  File "lg.py", line 314, in main
    lg_remote.get_session_id(get_pairing_key_from_user(lg_remote))
  File "lg.py", line 239, in get_pairing_key_from_user
    lg_remote.display_key_on_screen()
  File "lg.py", line 144, in display_key_on_screen
    headers=self._headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
root@raspberrypi:/home/pi/lgcommander#
`
Can you help me ?

**Comment by Domoteek** [comment] 2017-03-15 20:18
i try too 

nmap 192.168.1.100 --reason -vvv -Pn -p 3000,8080

`PORT     STATE  SERVICE    REASON
3000/tcp open   ppp        syn-ack
8080/tcp closed http-proxy reset
`

**Comment by ypid** [comment] 2017-03-15 20:28
Look at the command output you posted:

> Exception: Protocol not supported. See #1

This seems to be a duplicate of: https://github.com/ypid/lgcommander/issues/1

**Closed as completed by ypid** 2017-03-15 20:28 UTC

**Comment by Domoteek** [comment] 2017-03-16 06:14
ca m'aide !! comment je me suis retrouver ici ? le post je l'ai lu de long en large et ce n'est pas très clair

**Comment by ypid** [comment] 2017-03-16 06:31
I am sorry, I only understand English (and German). But I think you are saying that #1 is not very clear. Well, the script already said:

> Exception: Protocol not supported. See #1 

The protocol is not supported. Does currently not work with this script. I looked into the protocol but it is a completely different one and I don’t have a device to test with and no intention to add support for it myself.
